name: Deploy source code to Azure Spring Apps
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with soruce code
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to production step with soruce code
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: deploy
          service-name: ${{ secrets.AZURE_SPRING_APPS_NAME }}
          app-name: ${{ secrets.AZURE_SPRING_APP_NAME }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}
